### ISSUE TITLE
Adaptive Learning Master Issue

### ISSUE THREAD

**Issue by bee-san** [RustScan/RustScan#72]
This issue tracks multiple issues for the "adaptive learning" version of RustScan.
- [ ] #33 Adaptive Outbound SYN Timing to optimize speed of scanning
- [ ] #69 Recording of most inputted user ports to develop a custom "top X ports list" https://github.com/brandonskerritt/RustScan/issues/69#issuecomment-663884626
- [ ] Better ulimt auto-adaption support https://github.com/brandonskerritt/RustScan/issues?q=is%3Aissue+is%3Aopen+ulimit
- [ ] #71 Config File
