### ISSUE TITLE
Todo list for today

### ISSUE THREAD

**Issue by brandonskerritt** [RustScan/RustScan#86]
Because I, Brandon, need a todo list

- [x] * Submit to homebrew core
- [x] * Submit to awesome rust
https://github.com/rust-unofficial/awesome-rust/pull/933
- [x] * Submit to awesome security
- [x] * Finish ipv6
